# Generated by Django 5.2.8 on 2025-11-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='cvv',
            field=models.CharField(default='FAILED', max_length=16),
        ),
        migrations.AddField(
            model_name='accounts',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
